### PR TITLE
Fix Grammar + Interval shows end date if over >1 day

### LINKED ISSUE #175: [PE-D] UG Bug - Interface example in UG different from actual interface
Screenshot from my app (first launch):

UG section 2:

Minor GUI difference but consider updating the UG with new screenshots after each GUI update.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: wengfaing/ped#1

### LINKED ISSUE #193: [PE-D] Window cannot fit my 13 inch laptop screen
The application starts like this on my laptop and I cannot move or resize the window at all

When extended to my monitor, it fills out to both screens and still has some trouble resizing. Ultimately it fill the entire monitor after some meddling. 

Maybe the display resolution can be looked into?

Laptop Display Resolution : 3840 x 2160
Monitor Display Resolution: 1920 x 1080

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: pennhanlee/ped#8

### LINKED ISSUE #199: [PE-D] End date is not indicated, which is an issue if the event is long
End date is indicated in the `New Session Added...` part. However, on the panel on the right, the end date of the sessionis not specified. 

The session below has an end time way beyong 29 april, yet that is the only date shown in the column on the right.

The session below that was added, had a duration of a few thousand minutes, and the endtime shown was incorrect, showing 0000 instead.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: GeNiaaz/ped#6

### LINKED ISSUE #203: [PE-D] Inconsistency in the name of the file
Maybe change the file name in the UG to be FitEgo.jar instead?

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: leeyorktat/ped#1

### LINKED ISSUE #205: [PE-D] Missing documentation
If I'm not wrong, the user is also able to sort the list according to payment?

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: leeyorktat/ped#3

### LINKED ISSUE #208: [PE-D] Trivial grammar error
will serve as a* user guide
Made with* fitness instructors in mind

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: leeyorktat/ped#6

### LINKED ISSUE #209: [PE-D] Grammar errors
Just some small grammar errors

Sessions are timeslots*

It consists* of 

'The GUI similar to the below' does not sound grammatically correct I think. similar to the figure below?

display the commands* starting

prompt you with* an error message (I think?)

There are* no schedules assigned today

icons represent* different

use arrow keys* to

In case .... doesnt sound grammatically correct?

doesn't allow the* user

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: leeyorktat/ped#7

### LINKED ISSUE #212: [PE-D] Suggestion to better explain Schedules
Can consider making the first sentence clearer, can be confusing to the user I feel

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: leeyorktat/ped#10

### LINKED ISSUE #213: [PE-D] Inconsistency in terms used
Inconsistency in recognised

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: leeyorktat/ped#11

### LINKED ISSUE #214: [PE-D] Suggestion
Can consider using mark up for the caption of the figure similar to the commands shown below, to make it clearer for the user?

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: leeyorktat/ped#12

### LINKED ISSUE #215: [PE-D] Inconsistency in terms
Inconsistency in terms. Can consider changing?

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: leeyorktat/ped#13

### PR DESCRIPTION
**Pull request by kelvinvin**
image
fixes #213 and #199

### CODE REVIEW

File: src/main/java/seedu/address/model/session/Interval.java [hunk 1]
```diff
@@ -52,25 +53,56 @@ public LocalDateTime getStart() {
...
+        }
+    }
+
+    /**
+     * Returns true if the start and end time are on different days.
+     * @return Boolean value of whether start and end time are on different days
+     */
+    public boolean isPastMidnight() {
+        assert(this.getStart() != null && this.getEnd() != null);
+        return this.getEnd().truncatedTo(DAYS).isAfter(this.getStart().truncatedTo(DAYS));
```
Comment (benclmnt) [inline src/main/java/seedu/address/model/session/Interval.java:103]: What about 10 Feb - 9 Mar? Will it show the date?

Maybe add some test cases for this

**Review by benclmnt — COMMENTED** [review]
Other than that, looks good to me

File: src/main/java/seedu/address/model/session/Interval.java (hunk 1 above)
Comment (kelvinvin) [reply src/main/java/seedu/address/model/session/Interval.java:103]: Yup it'll show the date correctly! Bcos truncated returns a new LocalDateTime, not a int, so isBefore will work correctly. 

Just realised a issue though. What if I set start as 10 Feb 2017 and duration as a year. It'll display the start time and end time as the same.

Do I need another isPastNewYear? ... Or should I just change it to DDMMYYYY

Comment (kelvinvin) [reply src/main/java/seedu/address/model/session/Interval.java:103]: Nevermind, I think I'll add YYYY to any interval in the session time. Sat 13 Feb -> Sat 13 Feb 2020

**Comment by tanweijie123** [comment]
Is it possible to fix this tho? 
image

File: src/main/java/seedu/address/model/session/Interval.java (hunk 1 above)
Comment (benclmnt) [reply src/main/java/seedu/address/model/session/Interval.java:103]: Yea I guess for > 1 days, just display the full date or (can apply this to <= 1 day too, but this might clutter the screen tho)

Comment (kelvinvin) [reply src/main/java/seedu/address/model/session/Interval.java:103]: For the time field: Within a day, stay as 3.00pm - 4.00pm. Over 2 days, add year (e.g. 3.00pm to 01 Sep 2020 4.00pm)
For the header of each session card, I'm adding year regardless of duration le, because right now 18 Feb 2020 and 18 Feb 2021 both show as 18 Feb. Though its sorted, let's play safe hahah
