### PR TITLE
[PED] Overlapping session bug and update UG 

### LINKED ISSUE #200: [PE-D] Creating duplicate schedule shows wrong error message
When creating a schedule for the same session for the same person, the error message returned is `This schedule overlaps with an existing schedule`. Instead, it should tell the user that the duplicate event is added.

In this add, John Doe (5) is trying to be added to Sun 25 Oct (4) for the second time.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: GeNiaaz/ped#7

### LINKED ISSUE #211: [PE-D] Suggestion to make the example clearer
Understand that the example is trying to say that the edit command overwrites the gym field but may confuse the user with the additional fields. Can consider saying the example edits the name of the gym field but is keeping the rest of the fields the same (need to input again)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: leeyorktat/ped#9

### LINKED ISSUE #223: `sedit` allows for overlapping sessions
Steps to reproduce:

1. Delete data file
2. `sview p/all`
3. `sedit 2 at/26/10/2020 1200 t/500` <- change date, purpose is to make session 1 and 2 overlap.

### PR DESCRIPTION
**Pull request by maguireong**

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/session/EditSessionCommand.java [hunk 1]
```diff
@@ -73,7 +75,15 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_DUPLICATE_SESSION);
         }
 
+        for (int i = 0; i < lastShownList.size(); i++) {
```
Comment (dhafinrazaq) [inline src/main/java/seedu/address/logic/commands/session/EditSessionCommand.java]: should this check with all sessions in fitego, instead of just those that are shown?

Comment (maguireong) [reply src/main/java/seedu/address/logic/commands/session/EditSessionCommand.java]: Okay i'll change that, makes sense

File: src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java [hunk 2]
```diff
@@ -53,7 +53,7 @@
 
     public static final String MESSAGE_EDIT_SCHEDULE_SUCCESS = "Schedule Edited: \n%1$s";
     public static final String MESSAGE_NOT_EDITED = "At least one field to edit must be provided.";
-    public static final String MESSAGE_DUPLICATE_SCHEDULE = "This Schedule overlaps with an existing Schedule";
+    public static final String MESSAGE_DUPLICATE_SCHEDULE = "This Schedule already exists in the Schedule List";
```
Comment (dhafinrazaq) [inline src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java]: in case they think Schedule List is the "today's schedule" in home page and to be more consistent, would it be better to be
"The Schedule already exists in FitEgo"?

for duplicate client: "This Client already exists in the address book."

**Review by dhafinrazaq — APPROVED** [review]
looks good to me
